title: "The Desk of Karen Lee Field"
description: "Author of fantasy adventure and middle-grade mystery fiction."
baseurl: ""
url: "https://www.karenleefield.com"

date_format: "%-d %B %Y"

# Collections & defaults
permalink: /:categories/:year/:month/:day/:title/

paginate: 10
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-paginate

# Navigation (for header)
nav_links:
  left:
    - title: "The Desk of Karen Lee Field"
      url: "/"
  right:
    - title: "My Books"
      url: "/my-books/"
    - title: "For Writers"
      url: "/for-writers/"
    - title: "For Readers"
      url: "/for-readers/"
    - title: "Life's Side Quests"
      url: "/lifes-side-quests/"
    - title: "Archives"
      url: "/archives/"
    - title: "Contact"
      url: "/contact/"

# Defaults so title/subtitle show everywhere
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      subtitle: ""
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
      subtitle: ""

# Exclude these files from production site
exclude:
  - CNAME
  - Gemfile
  - README.md
  - templates/
