title: "The Desk of Karen Lee Field"
description: "Author of fantasy adventure and middle-grade mystery fiction."
baseurl: ""
url: "https://www.karenleefield.com"

markdown: kramdown
theme: null

collections:
  books:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /:categories/:title/

paginate: 10
paginate_path: "/blog/page:num"
